[package]
name = "diashow-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui_extras = { version = "0.28.1", features = ["image", "default"] }
env_logger = "0.11.3"
image = { version = "0.25.2", default-features = false, features = ["jpeg", "rayon"] }
